# Generated by Django 5.1.3 on 2024-11-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_id_note_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='uuid',
            new_name='id',
        ),
    ]
