# Generated by Django 5.1.3 on 2025-04-12 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
